# Generated by Django 3.1.6 on 2021-02-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0002_remove_games_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='playerId',
        ),
        migrations.AddField(
            model_name='games',
            name='player',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='raterprojectapi.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='timeToPlay',
            field=models.IntegerField(),
        ),
    ]
